---
abstract: 'The Chinese sentence generator.'
author:
  - 'Kang-min Liu, <gugod@gugod.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Lingua::ZH::Remix
name: Acme-Lingua-ZH-Remix
no_index:
  directory:
    - inc
    - t
requires:
  List::MoreUtils: 0
  Memoize: 0
  common::sense: 3
resources:
  license: http://opensource.org/licenses/mit-license.php
  repository: http://github.com/gugod/Acme-Lingua-ZH-Remix.git
version: 0.10
